### ISSUE TITLE
Material - CSS for material theme overriding that style property

### ISSUE THREAD

**Issue by dprock** [Audentio/xftheme-issues#95]
bug: CSS for material theme overriding that style propety. Fix: remove
```.discussionListItem .lastPostInfo .avatar {display: none;}```
and use style property instead
![2017-04-19_18-34-50](https://cloud.githubusercontent.com/assets/23287523/25197908/451e68d4-250b-11e7-9ae0-f8e44b80e226.jpg)

**Comment by nsaneman** [comment]
@dprock I beleive this was done deliberately because it's buggy when enabled. Once you have posts where the date is "Yesterday at 10:00 PM" the "PM" part will be displayed under the avatar. Other than this visual issue the page also looks too cluttered when avatars are shown. It's probably why they're not shown in the default XF theme too.
